version: "3"
services:
  postgresql:
    image: postgres:13.4
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - restoapp_network
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password # Later use secrets file
      POSTGRES_DB: resto_app

  resto_app:
    image: resto_app
    build:
      context: ./../
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://app_user:password@postgresql:5432/resto_app
      - LOG_LEVEL=INFO
      - LOG_FILE=server.log
    networks:
      - restoapp_network

networks:
  restoapp_network:
    driver: bridge

volumes:
  database:
    driver: local